chore: use case; convert to ps1

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-if [ $# -eq 0 ]; then
+if [ "$#" -eq 0 ] || [ "$1" = "h" ]; then
     echo "Usage: ./dev [lm cd pv]"
     echo "    l: start local                   m: cease local"
     echo "    c: start (and run) containers    d: cease (and remove) containers"
@@ -26,11 +26,12 @@ elif command -v docker &>/dev/null && command -v docker compose &>/dev/null; the
     cmd='docker'
     compose_cmd='docker compose'
 else
-    echo "E: Program requires either podman(-compose) or docker(-compose)."
+    echo "E: Program requires either podman(-compose) or docker(-compose)"
     exit 1
 fi
 
-if [ "$1" = "l" ]; then
+case $1 in
+l)
     if [ ! -d "logs" ]; then
         mkdir logs
     fi
@@ -40,9 +41,8 @@ if [ "$1" = "l" ]; then
     echo "Celery started with PID $CELERY_PID"
     flask -A src.cajon.main run
     exit $?
-fi
-
-if [ "$1" = "m" ]; then
+    ;;
+m)
     # if not killed along with the earlier process group
     # CELERY_PID=$(sed -n '1p' logs/pid.log)
     # if [ -n "$CELERY_PID" ]; then
@@ -53,29 +53,30 @@ if [ "$1" = "m" ]; then
         $cmd pod rm pod_cajon
     fi
     exit $?
-fi
-
-if [ "$1" = "c" ]; then
+    ;;
+c)
     $compose_cmd -p cajon -f compose.yaml up -d
     exit $?
-fi
-
-if [ "$1" = "d" ]; then
+    ;;
+d)
     $compose_cmd -p cajon -f compose.yaml down
     exit $?
-fi
-
-if [ "$1" = "p" ]; then
+    ;;
+p)
     $cmd system prune --force
     exit $?
-fi
-
-if [ "$1" = "v" ]; then
+    ;;
+v)
     $cmd system prune --volumes --force
     exit $?
-fi
-
-# if [ "$1" = "e" ]; then
+    ;;
+# e)
 #     $cmd system prune --all --force
 #     exit $?
-# fi
+#     ;;
+*)
+    echo "E: Invalid command"
+    echo "I: Pass h for help"
+    exit 1
+    ;;
+esac
